version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  obs-server:
    build:
      context: ../../
      dockerfile: ./docker/obs/server.Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/obs
      - PORT=4319
    ports:
      - "4319:4319"
    depends_on:
      - mongo
volumes:
  mongo_data: {}
